# build.gradle의 processResources에서 이 값들을 채워줍니다.
name: ${pluginNameActual}          # 예: SoulPlugin
version: ${version}                # 예: 1.0.3
main: ${mainClassPath}             # 예: com.yourname.soulplugin.SoulPlugin

api-version: '1.21'
author: YourNameOrAlias           # ★★★ 여러분의 이름이나 별명으로 변경
description: 영혼을 수집하고 사용하는 플러그인입니다. # ★★★ 설명 변경 가능

commands:
  souls:
    description: 영혼을 관리하고 아이템으로 인출합니다.
    usage: /souls [redeem|set|add|remove] ...
    aliases: [soul]
permissions:
  soulplugin.admin:
    description: 관리자용 영혼 관리 명령어를 사용합니다. (/souls set|add|remove)
    default: op